#Global Variable Center

title: Tamizh Selvan Johnson
email: your-email@example.com
github_username: TyroTamizh
description: >- # this means to ignore newlines until "baseurl:"
  Built to break. Tested to last.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tyrotamizh.github.io"

# Build settings
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed

collections:
  projects:
    output: true