#Global Variable Center

title: Tamizh Selvan Johnson
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Proactive Software engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tyrotamizh.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true